export default {
domain:"https://kite.ir/",
imgDomainRoutes:"https://kite.ir",
toursRoute:"/tours",
//domain:"http://kite.pargansystem.com/",
//imgDomainRoutes:"",
domainBlog:"https://kite.ir/blog/",
domainTour:"https://kite.ir/Tour/",
airportList:"Kite/AirportList",
hotelList:"kite/hotellist",
packageList: "kite/GetPackageList",
getPackageGroup: "kite/GetPackageGroup",
cityList: "kite/cityList",
weblogGroups: "Kite/GetWeblogGroup",
getPackages:"kite/getpackages",
PackageDetailFromTitle:"Kite/PackageDetailFromTitle",
GetPackageDetail:"Kite/GetPackageDetail",
GetPackageRules:"Kite/GetPackageRules",
userLogin:"kite/userLogin",
userRegister:"kite/userRegister",
book:"kite/book",
GetComment:"Kite/getComments",
PostComment:"Kite/writeComment",
}