export const actionTypes = {
  SET_ADULT_ARRAY :' SET_ADULT_ARRAY',
  SET_CHILD_ARRAY :' SET_CHILD_ARRAY',
  SET_ROOMS :' SET_ROOMS',
  SET_TOTAL :' SET_TOTAL',
  SET_INFANTCOUNT :' SET_INFANTCOUNT',
  SET_CHILD1COUNT :' SET_CHILD1COUNT',
  SET_CHILD2COUNT :' SET_CHILD2COUNT',
  SET_SELVALUES:'SET_SELVALUES',
  SET_ROOMRULES:'SET_ROOMRULES'
}
