export const actionTypes = {
    SEARCH_TOUR_FAILURE: 'SEARCH_TOUR_FAILURE',
    LOAD_SEARCH_TOUR: 'LOAD_SEARCH_TOUR',
    LOAD_SEARCH_TOUR_SUCCESS: 'LOAD_SEARCH_TOUR_SUCCESS',
    SET_FILTERED_RESULTS:'SET_FILTERED_RESULTS',
    SET_SEARCH_PARAMS:'SET_SEARCH_PARAMS'
  }
  